#!/bin/bash

# RMIT USAP Assignment 3 build_kernel
# Author : Aldo Irvine
# Email : s3692192@student.rmit.edu.au

# Command list :
ECHO=/bin/echo
GIT=/usr/bin/git
LS=/bin/ls

# 1. Checkout private repo (https://github.com/AldoIrvine111/usapA3
$ECHO "Checkout private repo"

$LS -a    # Check before git clone 
$GIT clone git@github.com:AldoIrvine111/usapA3
$LS -a    # Check after git clone
cd usapA3 || exit

echo "Git pull"
$GIT pull   #Pull latest branch
$LS -a
pwd

