#!/bin/bash

# RMIT USAP Assignment 3 build_kernel
# Author : Aldo Irvine
# Email : s3692192@student.rmit.edu.au

# Command list :
ECHO=/bin/echo
GIT=/usr/bin/git
LS=/bin/ls
CP=/bin/cp

# 1. Checkout private repo (https://github.com/AldoIrvine111/usapA3

# Use if statement to check if repo is not existed, cloned else pull to update latest changes made in repo.
$ECHO
$ECHO "1. Checkout private repo"

if [ -d usapA3 ]
then
	cd usapA3 || exit
	# Pull any changes made
	$ECHO "Directory usapA3 exist, pulling latest master branch"
	$GIT pull
       	$GIT log
	cd ..	
else
	$ECHO "Directory usapA3 does not exist, cloning repo using SSH"
	$GIT clone git@github.com:AldoIrvine111/usapA3.git
	$LS -a 
	$ECHO "Complete cloning repo (usapA3)"
fi


# 2. Checkout raspberry pi kernel repository

# Use if statement to check if repo is not existed, cloned else pull to update latest changes made in repo.

$ECHO 
$ECHO "2. Checkput raspbbery pi kernel repository"

if [ -d linux ]
then
	cd linux || exit
	# Pull any changes made
	$ECHO "Directory linux exist, pulling latest master branch"
	$GIT pull 
	cd ..
else
	$ECHO "Directory linux does not exist, cloning repo"
	$GIT clone --depth=1 https://github.com/raspberrypi/linux
	$LS -a 
	$ECHO "Complete cloning repo (linux)"
fi

$ECHO 
$LS -a 
$ECHO

# 3. Copy your ".config" file into the right place
# Copy .config file from usapA3 to linux 

cd usapA3 || exit

if [ -e .config ] 
then 
	$ECHO "Copying .config to ../linux"
	$CP .config ../linux
	cd ../linux || exit
else
	$ECHO ".config file does not exist"
fi

$ECHO
pwd
