#!/bin/bash

VCGENCMD=/usr/bin/vcgencmd
PRINTF=/usr/bin/printf
EGREP=/bin/egrep
ECHO=/bin/echo


$ECHO "Starting performance data. PID: $$"
$PRINTF "%-15s%5s\n" "TIME_STAMP" "TEMP(Celcius)" >> kernel_performance_data
$PRINTF "%20s\n" "----------------------------" >> kernel_performance_data

while true
do
	temp=$($VCGENCMD measure_temp | $EGREP -o  '[0-9]*\.[0-9]*')
	timestamp=$(date '+%H:%M:%S')
	$PRINTF "%-15s%5s\n" "$timestamp" "$temp" >> kernel_performance_data
	sleep 1
done

